development:
  adapter: postgresql
  encoding: unicode
  database: david_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: david_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: david_production
  pool: 5
